name: LOC Guard (Conversation)

on:
    pull_request:
        types: [opened, synchronize, reopened]
        # ignore branches
        branches-ignore:
            - main
            - "release/**"
            - "deploy/**"

env:
    LOC_THRESHOLD: "10" # Number of lines changed to trigger the guard
    GUARD_LEVEL: "1" # 0 = Warn (comment only), 1 = Block (CI fail)

jobs:
    loc-guard:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with: { fetch-depth: 0 }

            - name: LOC Guard
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              shell: bash
              run: |
                  set -euo pipefail
                  BASE_SHA="$(jq -r '.pull_request.base.sha' "$GITHUB_EVENT_PATH")"
                  HEAD_SHA="$(jq -r '.pull_request.head.sha' "$GITHUB_EVENT_PATH")"
                  PR_NUMBER="${{ github.event.pull_request.number }}"

                  git fetch --no-tags --depth=200 origin "$BASE_SHA" "$HEAD_SHA" >/dev/null 2>&1 || true
                  MERGE_BASE="$(git merge-base "$BASE_SHA" "$HEAD_SHA")"

                  EXCLUDES=( ':!vendor/**' ':!node_modules/**' ':!public/build/**' ':!storage/**'
                             ':!dist/**' ':!*.min.*' ':!composer.lock' ':!package-lock.json'
                             ':!yarn.lock' ':!pnpm-lock.yaml' )

                  read ADD DEL <<<"$(git diff --numstat "$MERGE_BASE" "$HEAD_SHA" -- "${EXCLUDES[@]}" | awk '{a+=$1; d+=$2} END{print a+0, d+0}')"
                  CHANGED=$((ADD + DEL))

                  if [ "$CHANGED" -ge "$LOC_THRESHOLD" ]; then
                    gh pr comment "$PR_NUMBER" \
                      --body "⚠️ **LOC Guard**: $CHANGED lines changed ( +$ADD / -$DEL ) — threshold **${LOC_THRESHOLD}** or more.
                      
                      Please consider splitting the PR or reducing diff size."
                    if [ "${GUARD_LEVEL}" = "1" ]; then
                      echo "::error::LOC Guard threshold exceeded"
                      exit 1
                    fi
                  else
                    gh pr comment "$PR_NUMBER" \
                      --body "✅ **LOC Guard**: $CHANGED lines changed ( +$ADD / -$DEL ) — under threshold **${LOC_THRESHOLD}**."
                  fi
